apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: monitoring-eks          # cluster name
  region: eu-central-1          # your region
  version: "1.31"               # a stable EKS version

availabilityZones:              # constrain to exactly 2 AZs
  - eu-central-1a
  - eu-central-1b

iam:
  withOIDC: true                # needed later for IRSA (ALB controller)

# vpc:
#   id: "vpc-01726edb057271e76"

managedNodeGroups:
  - name: ng-general
    amiFamily: AmazonLinux2023  # current EKS default going forward
    instanceType: t3.small     # adjust if you want
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    privateNetworking: true     # worker nodes in private subnets
    labels:
      role: general
    tags:
      Name: monitoring-eks-ng-general
    ssh:
      allow: false              # can enable & supply key later if you want

# Optional: turn on control-plane logs (useful for troubleshooting)
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]